upstream shortener {
    least_conn;
    server shortener-1:8080;
    server shortener-2:8080;
}

server {
    listen 80;

    location / {
        proxy_pass http://shortener;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
